package controllers;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.jfoenix.controls.JFXButton;

import javafx.animation.FadeTransition;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import model.NhanVien;
import model.TaiKhoan;

public class MainFrmController implements Initializable {
	@FXML
	private AnchorPane mainPanel;
	
    @FXML
    private JFXButton btnHoaDon;

    @FXML
    private JFXButton btnKhachHang;

    @FXML
    private JFXButton btnPhong;

    @FXML
    private JFXButton btnNhanVien;

    @FXML
    private JFXButton btnDichVu;
	// Event Listener on JFXButton.onAction
	@FXML
	public void quanLyThueTraAction(ActionEvent event) {
		// TODO Autogenerated
		String url = "/application/submenu/HoaDonPhong.fxml";
                loadScene(url);
	}
        
	// Event Listener on JFXButton.onAction
	@FXML
	public void quanLyKhachHangAction(ActionEvent event) {
		// TODO Autogenerated
		String url = "/application/submenu/QuanLyKhachHang.fxml";
        loadScene(url);
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void quanLyPhongAction(ActionEvent event) {
		// TODO Autogenerated
		String url = "/application/submenu/QuanLyPhong.fxml";
        loadScene(url);
	}

	// Event Listener on JFXButton.onAction
	@FXML
	public void quanLyNhanVienAction(ActionEvent event) {
		// TODO Autogenerated
		String url = "/application/submenu/QuanLyNhanVien.fxml";
        loadScene(url);
	}

	// Event Listener on Button.onAction
	@FXML
	public void dangXuatAction(ActionEvent event) {

		try {
			Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/application/DangNhapFXML.fxml"));
			Parent root = loader.load();
			DangNhapController controller = loader.getController();
			stage.setScene(new Scene(root));
			stage.setFullScreen(false);
			stage.setResizable(false);
			stage.centerOnScreen();
			stage.show();
		} catch (IOException ex) {
			Logger.getLogger(DangNhapController.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	public static NhanVien nhanVien;
	
	public static void setNhanVien(NhanVien nhanVien) {
		MainFrmController.nhanVien = nhanVien;
	}

	private void loadScene(String url) {
		FadeTransition fadeTransition = new FadeTransition();
		fadeTransition.setDuration(javafx.util.Duration.millis(300));
		fadeTransition.setNode(mainPanel);
		fadeTransition.setFromValue(1);
		fadeTransition.setToValue(0);
		fadeTransition.setOnFinished((ActionEvent event) -> {
			try {
				FXMLLoader loader = new FXMLLoader(getClass().getResource(url));
				Parent mainContent = loader.load();
				mainPanel.getChildren().setAll(mainContent);
			} catch (IOException ex) {
				ex.printStackTrace();
			}
			fadeIntTransion();
		});
		fadeTransition.play();
	}

	private void fadeIntTransion() {
		FadeTransition fadeTransition = new FadeTransition();
		fadeTransition.setDuration(javafx.util.Duration.millis(300));
		fadeTransition.setNode(mainPanel);
		fadeTransition.setFromValue(0);
		fadeTransition.setToValue(1);
		fadeTransition.play();
	}

	public void initDefault() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/application/submenu/HoaDonPhong.fxml"));
			Parent mainContent = loader.load();
			mainPanel.getChildren().clear();
			mainPanel.getChildren().removeAll(mainContent);
			mainPanel.getChildren().setAll(mainContent);
			
			if(nhanVien.getChucVu().equals("NHANVIEN")) {
				isNotAdmin();
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
	public void isNotAdmin() {
		btnDichVu.setVisible(false);
		btnHoaDon.setVisible(true);
		btnKhachHang.setVisible(true);
		btnNhanVien.setVisible(false);
		btnPhong.setVisible(true);
		
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		initDefault();
		
		
	}
}
